apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: production-sso
  namespace: rhsso
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
  instances: 1
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: ocp
  namespace: rhsso
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: OpenShift Container Platform
    enabled: true
    id: ocp
    realm: openshift
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: ocp-web-console
  namespace: rhsso
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  client:
    rootUrl: https://oauth-openshift.$(DOMAIN_NAME)
    enabled: true
    clientAuthenticatorType: client-secret
    redirectUris:
      - /oauth2callback/rh-sso
    clientId: ocp-web-console
    implicitFlowEnabled: false
    secret: 5a77e831-bb79-43ca-9c58-082c9a09301f
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    name: OpenShift Web Console
    defaultClientScopes:
      - email
      - profile
  realmSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - sso
    matchLabels:
      app: sso
