apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  installPlanApproval: Manual 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
