apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  metrics:
    enable: true
  server:
    allowUserDefinedWorkspaceNamespaces: false
    cheFlavor: codeready
    gitSelfSignedCert: false
    serverExposureStrategy: multi-host
    tlsSupport: true
    workspaceNamespaceDefault: <username>-codeready
  auth:
    externalIdentityProvider: false
    identityProviderClientId: ''
    identityProviderRealm: ''
    identityProviderURL: ''
    openShiftoAuth: true
    updateAdminPassword: false
  database:
    chePostgresDb: ''
    chePostgresHostName: ''
    chePostgresPort: ''
    externalDb: false
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 5Gi
    pvcStrategy: common
