apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-update-deployment
spec:
  description: This Task can be used to update image digest in a Git repo using kustomize
  params:
    - default: $(params.APP_MANIFESTS_GIT)
      name: GIT_REPOSITORY
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: 'quay.io/jstakun/hello-quarkus:latest'
      name: CURRENT_IMAGE
      type: string
    - default: quay.io/jstakun/hello-quarkus-dev
      name: NEW_IMAGE
      type: string
    - default: $(params.APP_IMAGE_TAG)
      name: NEW_TAG
      type: string
    - default: stage
      name: KUSTOMIZATION_PATH
      type: string
  results:
    - description: The commit SHA
      name: commit
  steps:
    - image: 'docker.io/alpine/git:v2.32.0'
      name: git-clone
      resources: {}
      script: |
        rm -rf git-update-digest-workdir
        git clone $(params.GIT_REPOSITORY) git-update-digest-workdir
      workingDir: $(workspaces.workspace.path)
    - image: 'k8s.gcr.io/kustomize/kustomize:v3.8.7'
      name: update-digest
      resources: {}
      script: >
        cd git-update-digest-workdir/$(params.KUSTOMIZATION_PATH) 

        /app/kustomize edit set image
        $(params.CURRENT_IMAGE)=$(params.NEW_IMAGE):$(params.NEW_TAG) 

        echo "##########################" 

        echo "### kustomization.yaml ###" 

        echo "##########################" 

        cat kustomization.yaml
      workingDir: $(workspaces.workspace.path)
    - env:
        - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
          value: $(workspaces.basic-auth.bound)
        - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
          value: $(workspaces.basic-auth.path)
        - name: HOME
          value: /root
      image: 'docker.io/alpine/git:v2.32.0'
      name: git-commit
      resources: {}
      script: >
        cd git-update-digest-workdir

        git config user.email "tekton-pipelines-ci@redhat.com"

        git config user.name "tekton-pipelines-ci"

        #git config --global url."$(params.GIT_REPOSITORY)".insteadOf
        https://github.com/

        git add $(params.KUSTOMIZATION_PATH)/kustomization.yaml

        # git commit -m "[$(context.pipelineRun.name)] Image digest updated"

        git commit -m "[ci] Image digest updated"

        if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ] ; then
          cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.git-credentials" "${HOME}/.git-credentials"
          cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.gitconfig" "${HOME}/.gitconfig"
          chmod 400 "${HOME}/.git-credentials"
          chmod 400 "${HOME}/.gitconfig"
        fi

        git remote add auth-origin $(params.GIT_REPOSITORY)

        git push auth-origin $(params.GIT_REVISION)

        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"

        EXIT_CODE="$?"

        if [ "$EXIT_CODE" != 0 ] ; then
          exit $EXIT_CODE
        fi

        # Make sure we don't add a trailing newline to the result!

        echo -n "$RESULT_SHA" > $(results.commit.path)
      workingDir: $(workspaces.workspace.path)
  workspaces:
    - description: The workspace consisting of maven project.
      name: workspace
    - description: Git credentials secret
      name: basic-auth
