apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rox-deployment-check-remote
spec:
  params:
    - description: >-
        Secret containing the address:port tuple for StackRox Central (example -
        rox.stackrox.io:443)
      name: rox_central_endpoint
      type: string
    - description: Secret containing the StackRox API token with CI permissions
      name: rox_api_token
      type: string
    - description: YAML file in the deployfiles workspace
      name: file-url
      type: string
  results:
    - description: Output of `roxctl deployment check`
      name: check_output
  steps:
    - env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: rox_api_token
              name: $(params.rox_api_token)
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: rox_central_endpoint
              name: $(params.rox_central_endpoint)
      image: centos
      name: rox-deployment-check
      resources: {}
      script: >-
        #!/usr/bin/env bash

        set +x

        curl -k $(params.file-url) --output /deployfile/deploy.yml 

        cat /deployfile/deploy.yml

        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN"
        https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output
        ./roxctl  > /dev/null; echo "Getting roxctl"

        chmod +x ./roxctl  > /dev/null

        ./roxctl deployment check --insecure-skip-tls-verify -e
        $ROX_CENTRAL_ENDPOINT -f /deployfile/deploy.yml 
  workspaces:
    - description: |
        The folder containing deployment files
      mountPath: /deployfile
      name: deployfiles

