apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: stage
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
      - cluster: test
        url: https://kubernetes.default.svc
      - cluster: cicd
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'sample-app-{{cluster}}'
    spec:
      project: sample-app
      source:
        repoURL: https://github.com/jstakun/openshift-gitops.git
        targetRevision: HEAD
        path: '{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: sample-app-{{cluster}}
