apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    logging.openshift.io/preview-vector-collector: enabled  
    argocd.argoproj.io/sync-wave: "4"
spec:
  managementState: Managed 
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  collection:
    type: vector
