commonLabels:
  app: hello-quarkus
  createdBy: "jstakun/openshift-gitops"
commonAnnotations:
  vcs-url: "https://github.com/jstakun/openshift-gitops"
resources:
- deployment.yaml
- service.yaml
- secure-route.yaml
- prometheus-service-monitor.yaml
- network-policy.yaml
