apiVersion: v1
kind: LimitRange
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: 2 
        memory: 2Gi 
      min:
        cpu: 4m 
        memory: 8Mi 
    - type: "Container"
      max:
        cpu: 2 
        memory: 2Gi 
      min:
        cpu: 4m 
        memory: 4Mi 
      default:
        cpu: 200m
        memory: 512Mi 
      defaultRequest:
        cpu: 100m
        memory: 256Mi 
