resources:
- configmap-maven-settings.yaml
- configmap-argocd-env.yaml  
- pipeline-security-check-pipeline.yaml           
- task-rox-image-check.yaml
- task-cosign.yaml                                
- task-rox-image-scan.yaml
- task-git-update-deployment.yaml                 
- task-sonarqube-scanner.yaml
- persistentvolumeclaim-workspace.yaml  
- task-redhat-codeready-dependency-analysis.yaml  
- task-zap-proxy.yaml
- pipeline-sample-app-secure.yaml       
- task-rox-deployment-check-remote.yaml
- pipeline-sample-app.yaml              
- task-rox-deployment-check.yaml
- sa-pipeline.yaml

secretGenerator:
- name: roxsecrets
  envs:
  - rhacs.properties
  options:
    disableNameSuffixHash: true
- name: argocd-env-secret
  envs: 
  - argocd.properties 
  options:
    disableNameSuffixHash: true
  
#patchesJSON6902:
#- target:
#    version: v1
#    kind: ServiceAccount
#    name: pipeline
#  patch: |-
#    - op: add
#      path: /secrets/name/-
#      value: quay-creds
