apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-sbom
spec:
  params:
    - default: ''
      description: Image to generate sbom.
      name: image
      type: string
    - default: spdx-json@2.2
      description: 'Output format as per https://docs.redhat.com/en/documentation/red_hat_trusted_profile_analyzer/1/html/reference_guide/creating-an-sbom-manifest-file_ref'
      name: output-format
      type: string
  steps:
    - args:
        - $(params.image)
        - '--scope'
        - all-layers
        - '--output'
        - $(params.output-format)
      image: 'registry.access.redhat.com/rh-syft-tech-preview/syft-rhel9:1.4.1'
      name: generate-sbom
      resources: {}
      workingDir: /workspace/source
  workspaces:
    - name: source

