apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gatling
spec:
  params:
  - name: DURATION
    description: The duration of running simulations
    type: string
    default: "30"
  - name: CONCURRENT_USERS
    description: The number of concurrent users
    type: string
    default: "10"
  - name: APPLICATION_NAME
    type: string
    default: "app"
  - name: APP_URL
    description: The application under test url
  - name: ALLURE_HOST
    type: string
    description: "Allure Host"
    default: "http://allure:5050"
  - name: ALLURE_SECRET
    type: string
    description: Secret containing Allure credentials
    default: allure-auth
  workspaces:
  - description: The workspace consisting of maven project.
    name: simulations      
  steps:
    - name: run-tests
      image: quay.io/siamaksade/gatling:latest
      env:
        - name: PIPELINERUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
        - name: ALLURE_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.ALLURE_SECRET)
              key: username
        - name: ALLURE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.ALLURE_SECRET)
              key: password    
      script: |
        #!/usr/bin/env bash

        # set simulation params
        export JAVA_OPTS="-DtestDuration=$(params.CONCURRENT_USERS) -DuserCount=$(params.DURATION) -Dserver=$(params.APP_URL)"

        # run simulation
        /opt/gatling/bin/gatling.sh -rd "App Performance Test" -sf $(workspaces.simulations.path)

        # upload results
        echo "Sending results to Allure"
        curl -sLo send_results.sh https://raw.githubusercontent.com/eformat/allure/main/scripts/send_results.sh && chmod 755 send_results.sh
        ./send_results.sh $(params.APPLICATION_NAME) \
        /opt \
        ${ALLURE_USERNAME} \
        ${ALLURE_PASSWORD} \
        $(params.ALLURE_HOST) \
        gatling/results
        echo "---------------------------"
        echo "Open this link to see detailed report:"
        echo $(params.ALLURE_HOST)/allure-docker-service/projects/$(params.APPLICATION_NAME)/reports/latest/index.html
         
